language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - jruby-18mode # JRuby in 1.8 mode
  - jruby-19mode # JRuby in 1.9 mode
  - 2.0.0
  - 2.1.1
  - 2.1.2
  - rbx-18mode
  - rbx-19mode


script: "bundle exec rake test"

matrix:
  allow_failures:
    - rvm: jruby-18mode
    - rvm: rbx-18mode
    - rvm: rbx-19mode

notifications:
  email:
    on_success: always
