language: ruby
rvm:
  - 1.9.3
  - jruby-19mode # JRuby in 1.9 mode
  - 2.0.0
  - 2.1.1
  - 2.1.2
  - 2.2.0
  - rbx-19mode


script: "bundle exec rake test"

matrix:
  allow_failures:
    - rvm: rbx-19mode

notifications:
  email:
    on_success: always
