language: ruby

before_install:
  - gem install bundler
  
rvm:
  - 1.9.3
  - jruby-19mode # JRuby in 1.9 mode
  - 2.0.0
  - 2.1.2
  - 2.2.0
  - 2.3.0
  - rbx-19mode
  - ruby-head


script: "bundle exec rake test"

matrix:
  allow_failures:
    - rvm: rbx-19mode
    - rvm: ruby-head

notifications:
  email:
    on_success: always
